version: 2

project_name: go-licenses-config

builds:
  - id: go-licenses-config
    main: .
    binary: ./go-licenses-config
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    goos:
      - linux
    goarch:
      - amd64

kos:
  - id: go-licenses-config
    build: go-licenses-config
    base_image: ghcr.io/juli3nk/static:20260901
    repositories:
      - ghcr.io/juli3nk/go-licenses-config
