name: release

on:
  push:
    branches:
      - main

jobs:
  deps:
    uses: juli3nk/ci-shared/.github/workflows/go-deps.yaml@main
    with:
      go_version: ${{ vars.GO_VERSION }}
      check_licenses: false

  release:
    permissions:
      contents: write
    needs: deps
    uses: juli3nk/ci-shared/.github/workflows/release.yaml@main

  publish:
    permissions:
      contents: read
      packages: write
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: juli3nk/ci-shared/.github/workflows/go-publish.yaml@main
    with:
      released: ${{ needs.release.outputs.released }}
      tag: ${{ needs.release.outputs.tag }}
